# Generated by Django 4.2.6 on 2023-10-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('qes', models.CharField(max_length=250)),
                ('ans', models.CharField(max_length=400)),
                ('answer_by', models.TextField()),
                ('posted_date', models.DateField()),
                ('picture', models.TextField()),
                ('up_count', models.IntegerField()),
                ('downvote_count', models.IntegerField()),
            ],
        ),
    ]
