# Generated by Django 4.2.6 on 2023-11-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like_used',
            field=models.CharField(default=0, max_length=230),
            preserve_default=False,
        ),
    ]
